"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { ImpactDashboard, CentreSubjectBreakdown } from "./server";

const ORANGE = "#E8871E";
const HEADING = "#2D2117";
const MUTED = "#9C8B7A";
const GREEN = "#22C55E";
const CREAM = "#FFF9F1";
const BLUE = "#3B82F6";
const PURPLE = "#8B5CF6";
const YELLOW = "#EAB308";
const RED = "#EF4444";

export type ReportScope = "platform" | "org";

async function loadLogoDataUrl(): Promise<string | null> {
  try {
    const res = await fetch("/logo.png");
    const blob = await res.blob();
    return await new Promise<string>((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.readAsDataURL(blob);
    });
  } catch {
    return null;
  }
}

function truncate(str: string, max: number): string {
  return str.length > max ? str.slice(0, max - 1) + "…" : str;
}

export async function generateImpactReport(
  data: ImpactDashboard,
  userName: string,
  orgName: string,
  centreName?: string,
  scope: ReportScope = "org",
) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  const timeStr = now.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" });

  const logoDataUrl = await loadLogoDataUrl();

  let pageNum = 1;

  // ─── Helper functions ───

  function newPage() {
    doc.addPage();
    pageNum++;
    doc.setFillColor(CREAM);
    doc.rect(0, 0, pageWidth, pageHeight, "F");
  }

  function addFooter() {
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text("Generated by EduFleet LMS · Confidential", margin, pageHeight - 10);
    doc.text(`Page ${pageNum}`, pageWidth - margin, pageHeight - 10, { align: "right" });
  }

  function sectionHeader(title: string, y: number): number {
    doc.setFontSize(16);
    doc.setTextColor(HEADING);
    doc.text(title, margin, y);
    doc.setDrawColor(ORANGE);
    doc.setLineWidth(0.4);
    doc.line(margin, y + 3, margin + 55, y + 3);
    return y + 10;
  }

  function drawMetricBox(x: number, y: number, w: number, value: string, label: string, color: string) {
    doc.setFillColor("#FFFFFF");
    doc.roundedRect(x, y, w, 28, 4, 4, "F");
    doc.setDrawColor("#E8D5C0");
    doc.roundedRect(x, y, w, 28, 4, 4, "S");
    doc.setFontSize(18);
    doc.setTextColor(color);
    doc.text(value, x + w / 2, y + 13, { align: "center" });
    doc.setFontSize(7);
    doc.setTextColor(MUTED);
    doc.text(label, x + w / 2, y + 22, { align: "center" });
  }

  // ─── Chart: Stacked Horizontal Bar (Mastery Distribution) ───

  function drawStackedBar(
    y: number,
    segments: { label: string; value: number; color: string }[],
  ): number {
    const total = segments.reduce((s, seg) => s + seg.value, 0);
    if (total === 0) {
      doc.setFontSize(9);
      doc.setTextColor(MUTED);
      doc.text("No quiz attempts recorded.", margin, y + 5);
      return y + 12;
    }

    const barH = 10;
    let cx = margin;
    // Draw segments
    for (const seg of segments) {
      const w = (seg.value / total) * contentWidth;
      if (w > 0) {
        doc.setFillColor(seg.color);
        doc.rect(cx, y, w, barH, "F");
        // Show percentage inside if wide enough
        if (w > 12) {
          doc.setFontSize(7);
          doc.setTextColor("#FFFFFF");
          doc.text(`${Math.round((seg.value / total) * 100)}%`, cx + w / 2, y + barH / 2 + 2, { align: "center" });
        }
        cx += w;
      }
    }
    // Round the bar ends
    doc.setDrawColor(CREAM);
    doc.setLineWidth(0);

    // Legend below
    y += barH + 5;
    let lx = margin;
    doc.setFontSize(7.5);
    for (const seg of segments) {
      doc.setFillColor(seg.color);
      doc.rect(lx, y, 3, 3, "F");
      doc.setTextColor(HEADING);
      const label = `${seg.label}: ${seg.value} (${Math.round((seg.value / total) * 100)}%)`;
      doc.text(label, lx + 5, y + 2.5);
      lx += doc.getTextWidth(label) + 10;
      if (lx > pageWidth - margin - 20) { lx = margin; y += 5; }
    }
    return y + 8;
  }

  // ─── Chart: Horizontal Bar Chart ───

  function drawHorizontalBars(
    y: number,
    items: { label: string; value: number; suffix?: string; annotation?: string; color?: string }[],
    maxValue?: number,
  ): number {
    if (items.length === 0) {
      doc.setFontSize(9);
      doc.setTextColor(MUTED);
      doc.text("No data available.", margin, y);
      return y + 8;
    }

    const barH = 7;
    const gap = 3;
    const labelW = 40;
    const barAreaW = contentWidth - labelW - 20;
    const max = maxValue ?? Math.max(...items.map((i) => i.value), 1);
    const shown = items.slice(0, 12);

    for (const item of shown) {
      // Label
      doc.setFontSize(8);
      doc.setTextColor(HEADING);
      doc.text(truncate(item.label, 22), margin, y + barH / 2 + 2);

      // Bar background
      doc.setFillColor("#E5E7EB");
      doc.roundedRect(margin + labelW, y, barAreaW, barH, 2, 2, "F");

      // Bar fill
      const fillW = max > 0 ? (item.value / max) * barAreaW : 0;
      if (fillW > 0) {
        doc.setFillColor(item.color ?? ORANGE);
        doc.roundedRect(margin + labelW, y, Math.max(fillW, 2), barH, 2, 2, "F");
      }

      // Value at end
      doc.setFontSize(7.5);
      doc.setTextColor(HEADING);
      const valText = `${item.value}${item.suffix ?? ""}`;
      doc.text(valText, margin + labelW + barAreaW + 2, y + barH / 2 + 2);

      // Annotation (e.g. learner count) on the right
      if (item.annotation) {
        doc.setFontSize(6.5);
        doc.setTextColor(MUTED);
        doc.text(item.annotation, margin + labelW + barAreaW + 14, y + barH / 2 + 2);
      }

      y += barH + gap;
    }

    if (items.length > 12) {
      doc.setFontSize(7);
      doc.setTextColor(MUTED);
      doc.text(`… and ${items.length - 12} more`, margin, y + 2);
      y += 6;
    }

    return y;
  }

  // ─── Chart: Line Chart (30-day activity) ───

  function drawLineChart(
    y: number,
    series: { data: number[]; color: string; label: string }[],
    xLabels: string[],
    chartHeight: number = 55,
  ): number {
    const hasData = series.some((s) => s.data.some((v) => v > 0));
    if (!hasData) {
      doc.setFontSize(9);
      doc.setTextColor(MUTED);
      doc.text("No activity recorded in the last 30 days.", margin, y + 10);
      return y + 18;
    }

    const chartX = margin + 15; // leave room for Y labels
    const chartW = contentWidth - 20;
    const chartY = y;

    // Find max across all series
    const allValues = series.flatMap((s) => s.data);
    const maxVal = Math.max(...allValues, 1);
    const niceMax = Math.ceil(maxVal / 5) * 5 || 5;

    // Y-axis gridlines
    doc.setLineWidth(0.1);
    doc.setDrawColor("#D1D5DB");
    for (let i = 0; i <= 4; i++) {
      const gy = chartY + chartHeight - (i / 4) * chartHeight;
      doc.line(chartX, gy, chartX + chartW, gy);
      doc.setFontSize(6);
      doc.setTextColor(MUTED);
      doc.text(String(Math.round((niceMax / 4) * i)), chartX - 2, gy + 1.5, { align: "right" });
    }

    // X-axis labels (show every 5th day)
    const pointCount = xLabels.length;
    for (let i = 0; i < pointCount; i++) {
      if (i % 5 === 0 || i === pointCount - 1) {
        const px = chartX + (i / Math.max(pointCount - 1, 1)) * chartW;
        doc.setFontSize(5.5);
        doc.setTextColor(MUTED);
        const shortDate = xLabels[i].slice(5); // MM-DD
        doc.text(shortDate, px, chartY + chartHeight + 4, { align: "center" });
      }
    }

    // Draw series
    for (const s of series) {
      doc.setDrawColor(s.color);
      doc.setLineWidth(0.5);

      let prevX = 0;
      let prevY = 0;
      for (let i = 0; i < s.data.length; i++) {
        const px = chartX + (i / Math.max(s.data.length - 1, 1)) * chartW;
        const py = chartY + chartHeight - (s.data[i] / niceMax) * chartHeight;

        if (i > 0) {
          doc.line(prevX, prevY, px, py);
        }

        // Draw dot
        doc.setFillColor(s.color);
        doc.circle(px, py, 0.6, "F");

        prevX = px;
        prevY = py;
      }
    }

    // Legend
    const ly = chartY + chartHeight + 10;
    let lx = chartX;
    doc.setFontSize(7);
    for (const s of series) {
      doc.setFillColor(s.color);
      doc.rect(lx, ly - 2, 4, 2, "F");
      doc.setTextColor(HEADING);
      doc.text(s.label, lx + 6, ly);
      lx += doc.getTextWidth(s.label) + 14;
    }

    return ly + 6;
  }

  // ─── Chart: Completion Funnel ───

  function drawFunnel(y: number, stages: { label: string; value: number; color: string }[]): number {
    if (stages.length === 0 || stages[0].value === 0) {
      doc.setFontSize(9);
      doc.setTextColor(MUTED);
      doc.text("No chapter data to display.", margin, y + 5);
      return y + 12;
    }

    const maxWidth = 140;
    const stageH = 20;
    const gap = 6;
    const centerX = pageWidth / 2;
    const topVal = stages[0].value;

    for (let i = 0; i < stages.length; i++) {
      const stage = stages[i];
      const w = topVal > 0 ? Math.max((stage.value / topVal) * maxWidth, 30) : 30;

      // Draw stage rectangle
      doc.setFillColor(stage.color);
      doc.roundedRect(centerX - w / 2, y, w, stageH, 3, 3, "F");

      // Label inside
      doc.setFontSize(10);
      doc.setTextColor("#FFFFFF");
      doc.text(`${stage.label}: ${stage.value}`, centerX, y + stageH / 2 + 3, { align: "center" });

      // Conversion arrow between stages
      if (i < stages.length - 1) {
        const nextStage = stages[i + 1];
        const pct = stage.value > 0 ? Math.round((nextStage.value / stage.value) * 100) : 0;
        doc.setFontSize(8);
        doc.setTextColor(MUTED);
        doc.text(`↓ ${pct}%`, centerX, y + stageH + gap / 2 + 2, { align: "center" });
      }

      y += stageH + gap;
    }

    return y;
  }

  // ═══════════════════════════════════════════
  // PAGE 1: COVER
  // ═══════════════════════════════════════════

  doc.setFillColor(CREAM);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  if (logoDataUrl) {
    const logoW = 70;
    const logoH = logoW * (768 / 1366);
    doc.addImage(logoDataUrl, "PNG", (pageWidth - logoW) / 2, 45, logoW, logoH);
  }

  doc.setFontSize(28);
  doc.setTextColor(HEADING);
  const title = scope === "platform" ? "Platform Impact Report" : "Impact Analytics Report";
  doc.text(title, pageWidth / 2, 100, { align: "center" });

  doc.setDrawColor(ORANGE);
  doc.setLineWidth(0.5);
  doc.line(pageWidth / 2 - 40, 110, pageWidth / 2 + 40, 110);

  doc.setFontSize(12);
  doc.setTextColor(MUTED);
  doc.text(dateStr, pageWidth / 2, 125, { align: "center" });
  doc.text(timeStr, pageWidth / 2, 133, { align: "center" });

  doc.setFontSize(11);
  doc.setTextColor(HEADING);
  doc.text(`Generated by: ${userName}`, pageWidth / 2, 155, { align: "center" });
  if (scope === "platform") {
    doc.text(`${data.organizations.length} Organizations · ${data.centres.length} Centres`, pageWidth / 2, 165, { align: "center" });
  } else {
    doc.text(`Organization: ${orgName}`, pageWidth / 2, 165, { align: "center" });
    if (centreName) {
      doc.text(`Centre: ${centreName}`, pageWidth / 2, 175, { align: "center" });
    }
  }

  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  doc.text(`${data.totalLearners} learners · ${data.totalChapters} chapters · ${data.totalQuizAttempts} quiz attempts`, pageWidth / 2, 200, { align: "center" });

  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("Confidential · For internal use only", pageWidth / 2, pageHeight - 20, { align: "center" });

  addFooter();

  // ═══════════════════════════════════════════
  // PAGE 2: EXECUTIVE SUMMARY
  // ═══════════════════════════════════════════

  newPage();
  let ey = sectionHeader("Executive Summary", 25);

  const boxW = (contentWidth - 15) / 4;
  drawMetricBox(margin, ey, boxW, `${data.completedChapters}/${data.totalChapters}`, "Chapters Completed", ORANGE);
  drawMetricBox(margin + boxW + 5, ey, boxW, `${data.completionRate}%`, "Completion Rate", data.completionRate >= 50 ? GREEN : ORANGE);
  drawMetricBox(margin + (boxW + 5) * 2, ey, boxW, `${data.activeLearners}`, "Active Learners (7d)", GREEN);
  drawMetricBox(margin + (boxW + 5) * 3, ey, boxW, data.avgQuizScore != null ? `${data.avgQuizScore}%` : "—", "Avg Quiz Score", PURPLE);

  ey += 36;
  doc.setFontSize(10);
  doc.setTextColor(HEADING);

  const summaryLines: string[] = [];
  if (scope === "platform") {
    summaryLines.push(`This platform report covers ${data.organizations.length} organization${data.organizations.length !== 1 ? "s" : ""}, ${data.centres.length} centre${data.centres.length !== 1 ? "s" : ""}, and ${data.totalLearners} learner${data.totalLearners !== 1 ? "s" : ""}.`);
  } else {
    summaryLines.push(`This report covers ${data.totalLearners} learner${data.totalLearners !== 1 ? "s" : ""} across ${data.centres.length} centre${data.centres.length !== 1 ? "s" : ""}.`);
  }
  summaryLines.push(`Overall completion rate is ${data.completionRate}% with ${data.completedChapters} of ${data.totalChapters} chapters completed.`);
  if (data.activeLearners > 0) {
    summaryLines.push(`${data.activeLearners} learner${data.activeLearners !== 1 ? "s were" : " was"} active in the last 7 days.`);
  }
  if (data.totalQuizAttempts > 0) {
    summaryLines.push(`${data.totalQuizAttempts} quiz attempt${data.totalQuizAttempts !== 1 ? "s" : ""} recorded with an average score of ${data.avgQuizScore ?? 0}%.`);
  }
  const lowPerformers = data.centres.filter((c) => c.completionRate < 30 && c.learnerCount > 0);
  if (lowPerformers.length > 0) {
    summaryLines.push(`${lowPerformers.length} centre${lowPerformers.length !== 1 ? "s are" : " is"} below 30% completion and may need attention.`);
  }

  for (const line of summaryLines) {
    doc.text(line, margin, ey);
    ey += 7;
  }

  // Mastery stacked bar
  ey += 6;
  doc.setFontSize(12);
  doc.setTextColor(HEADING);
  doc.text("Quiz Mastery Distribution", margin, ey);
  ey += 5;

  ey = drawStackedBar(ey, [
    { label: "Mastery (90%+)", value: data.masteryDistribution.mastery, color: GREEN },
    { label: "Proficient (70–89%)", value: data.masteryDistribution.proficient, color: BLUE },
    { label: "Developing (50–69%)", value: data.masteryDistribution.developing, color: YELLOW },
    { label: "Needs Practice (<50%)", value: data.masteryDistribution.needs_practice, color: RED },
  ]);

  addFooter();

  // ═══════════════════════════════════════════
  // PAGE 3: DAILY ACTIVITY TREND (LINE CHART)
  // ═══════════════════════════════════════════

  newPage();
  let dy = sectionHeader("30-Day Activity Trend", 25);

  const xLabels = data.dailyActivity.map((d) => d.date);
  dy = drawLineChart(
    dy,
    [
      { data: data.dailyActivity.map((d) => d.lessonsWatched), color: BLUE, label: "Lessons Watched" },
      { data: data.dailyActivity.map((d) => d.quizAttempts), color: PURPLE, label: "Quiz Attempts" },
      { data: data.dailyActivity.map((d) => d.chaptersCompleted), color: GREEN, label: "Chapters Completed" },
    ],
    xLabels,
  );

  // Quick stats row below chart
  dy += 8;
  const totalLessons30d = data.dailyActivity.reduce((s, d) => s + d.lessonsWatched, 0);
  const totalQuizzes30d = data.dailyActivity.reduce((s, d) => s + d.quizAttempts, 0);
  const peakDay = data.dailyActivity.reduce((best, d) => (d.lessonsWatched + d.quizAttempts > best.lessonsWatched + best.quizAttempts ? d : best), data.dailyActivity[0]);

  doc.setFontSize(9);
  doc.setTextColor(HEADING);
  doc.text(`Total lessons watched (30d): ${totalLessons30d}`, margin, dy);
  doc.text(`Total quiz attempts (30d): ${totalQuizzes30d}`, margin + 65, dy);
  if (peakDay) {
    doc.text(`Peak day: ${peakDay.date} (${peakDay.lessonsWatched + peakDay.quizAttempts} activities)`, margin + 125, dy);
  }

  addFooter();

  // ═══════════════════════════════════════════
  // PAGE 4: SCOPE-SPECIFIC CHART
  // Platform → Org Comparison
  // Org → Subject-wise Completion
  // ═══════════════════════════════════════════

  newPage();

  if (scope === "platform") {
    // ─── Organization Comparison ───
    let oy = sectionHeader("Organization Comparison", 25);

    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text("Completion rate by organization (ranked)", margin, oy);
    oy += 6;

    const orgItems = [...data.organizations]
      .sort((a, b) => b.completionRate - a.completionRate)
      .map((org) => ({
        label: org.name,
        value: org.completionRate,
        suffix: "%",
        annotation: `${org.learnerCount} learners · ${org.centreCount} centres`,
        color: org.completionRate >= 50 ? GREEN : ORANGE,
      }));

    oy = drawHorizontalBars(oy, orgItems, 100);

    // Org summary table below
    if (oy + 50 < pageHeight - 20) {
      oy += 6;
      autoTable(doc, {
        startY: oy,
        margin: { left: margin, right: margin },
        head: [["Organization", "Centres", "Learners", "Active 7d", "Chapters", "Completion", "Quiz Avg"]],
        body: data.organizations.map((o) => [
          o.name,
          String(o.centreCount),
          String(o.learnerCount),
          String(o.activeLearners),
          `${o.completedChapters}/${o.totalChapters}`,
          `${o.completionRate}%`,
          o.avgQuizScore != null ? `${o.avgQuizScore}%` : "—",
        ]),
        headStyles: { fillColor: ORANGE, textColor: "#FFFFFF", fontStyle: "bold", fontSize: 7.5 },
        bodyStyles: { fontSize: 7.5, textColor: HEADING },
        alternateRowStyles: { fillColor: "#FFF5EB" },
        styles: { cellPadding: 2.5 },
      });
    }
  } else {
    // ─── Subject-wise Chapter Completion (aggregated across centres) ───
    let sy = sectionHeader("Subject-wise Completion", 25);

    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text("Aggregated across all centres in this organization", margin, sy);
    sy += 6;

    // Aggregate subjects from all centres' subjectBreakdown
    const subjAgg = new Map<string, { total: number; completed: number; quizSum: number; quizCount: number }>();
    for (const centre of data.centres) {
      for (const sb of centre.subjectBreakdown ?? []) {
        const existing = subjAgg.get(sb.name) ?? { total: 0, completed: 0, quizSum: 0, quizCount: 0 };
        existing.total += sb.totalChapters;
        existing.completed += sb.completedChapters;
        if (sb.avgQuizScore != null) {
          existing.quizSum += sb.avgQuizScore;
          existing.quizCount++;
        }
        subjAgg.set(sb.name, existing);
      }
    }

    const subjItems = Array.from(subjAgg.entries())
      .sort(([, a], [, b]) => {
        const ra = a.total > 0 ? a.completed / a.total : 0;
        const rb = b.total > 0 ? b.completed / b.total : 0;
        return rb - ra;
      })
      .map(([name, d]) => {
        const pct = d.total > 0 ? Math.round((d.completed / d.total) * 100) : 0;
        const quizAvg = d.quizCount > 0 ? Math.round(d.quizSum / d.quizCount) : null;
        return {
          label: name,
          value: pct,
          suffix: "%",
          annotation: `${d.completed}/${d.total} chapters${quizAvg != null ? ` · Quiz: ${quizAvg}%` : ""}`,
          color: pct >= 50 ? GREEN : ORANGE,
        };
      });

    sy = drawHorizontalBars(sy, subjItems, 100);

    // Subject breakdown table
    if (sy + 40 < pageHeight - 20 && subjItems.length > 0) {
      sy += 6;
      autoTable(doc, {
        startY: sy,
        margin: { left: margin, right: margin },
        head: [["Subject", "Chapters Done", "Completion %", "Avg Quiz Score"]],
        body: Array.from(subjAgg.entries()).map(([name, d]) => [
          name,
          `${d.completed}/${d.total}`,
          `${d.total > 0 ? Math.round((d.completed / d.total) * 100) : 0}%`,
          d.quizCount > 0 ? `${Math.round(d.quizSum / d.quizCount)}%` : "—",
        ]),
        headStyles: { fillColor: ORANGE, textColor: "#FFFFFF", fontStyle: "bold", fontSize: 8 },
        bodyStyles: { fontSize: 8, textColor: HEADING },
        alternateRowStyles: { fillColor: "#FFF5EB" },
        styles: { cellPadding: 2.5 },
      });
    }
  }

  addFooter();

  // ═══════════════════════════════════════════
  // PAGE 5: COMPLETION FUNNEL
  // ═══════════════════════════════════════════

  newPage();
  let fy = sectionHeader("Completion Funnel", 25);

  doc.setFontSize(9);
  doc.setTextColor(MUTED);
  doc.text("Chapter progression: Total → Started → Completed", margin, fy);
  fy += 8;

  // Compute "started" chapters estimate
  const totalWatchedLessons = data.centres.reduce((s, c) => s + c.watchedLessons, 0);
  const totalLessonsAll = data.centres.reduce((s, c) => s + c.totalLessons, 0);
  const startedRatio = totalLessonsAll > 0 ? totalWatchedLessons / totalLessonsAll : 0;
  const startedChapters = Math.max(
    data.completedChapters,
    Math.round(data.totalChapters * startedRatio),
  );

  fy = drawFunnel(fy, [
    { label: "Total Chapters", value: data.totalChapters, color: "#94A3B8" },
    { label: "Started", value: startedChapters, color: ORANGE },
    { label: "Completed", value: data.completedChapters, color: GREEN },
  ]);

  // Additional funnel stats
  fy += 6;
  doc.setFontSize(9);
  doc.setTextColor(HEADING);
  const startRate = data.totalChapters > 0 ? Math.round((startedChapters / data.totalChapters) * 100) : 0;
  const finishRate = startedChapters > 0 ? Math.round((data.completedChapters / startedChapters) * 100) : 0;
  doc.text(`Start rate: ${startRate}%  ·  Finish rate: ${finishRate}%  ·  Overall: ${data.completionRate}%`, margin, fy);

  addFooter();

  // ═══════════════════════════════════════════
  // PAGE 6: CENTRE COMPARISON CHART
  // ═══════════════════════════════════════════

  if (data.centres.length > 1) {
    newPage();
    let cy = sectionHeader("Centre Comparison", 25);

    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text("Ranked by completion rate", margin, cy);
    cy += 6;

    const centreItems = [...data.centres]
      .sort((a, b) => b.completionRate - a.completionRate)
      .map((c) => ({
        label: c.name,
        value: c.completionRate,
        suffix: "%",
        annotation: `${c.learnerCount} learners · ${c.mode === "offline" ? "Offline" : "Online"}`,
        color: c.completionRate >= 50 ? GREEN : ORANGE,
      }));

    cy = drawHorizontalBars(cy, centreItems, 100);

    addFooter();
  }

  // ═══════════════════════════════════════════
  // PAGE 7: CENTRE PERFORMANCE TABLE
  // ═══════════════════════════════════════════

  newPage();
  const ty = sectionHeader("Centre Performance", 25);

  autoTable(doc, {
    startY: ty,
    margin: { left: margin, right: margin },
    head: [["Centre", "Mode", "Learners", "Active 7d", "Completion", "Chapters", "Quiz Avg", "Last Activity"]],
    body: data.centres.map((c) => [
      c.name,
      c.mode === "offline" ? "Offline" : "Online",
      String(c.learnerCount),
      String(c.activeLearners),
      `${c.completionRate}%`,
      `${c.completedChapters}/${c.totalChapters}`,
      c.avgQuizScore != null ? `${c.avgQuizScore}%` : "—",
      c.lastActivityAt ? new Date(c.lastActivityAt).toLocaleDateString("en-IN", { day: "numeric", month: "short" }) : "—",
    ]),
    headStyles: { fillColor: ORANGE, textColor: "#FFFFFF", fontStyle: "bold", fontSize: 8 },
    bodyStyles: { fontSize: 8, textColor: HEADING },
    alternateRowStyles: { fillColor: "#FFF5EB" },
    styles: { cellPadding: 3 },
  });

  addFooter();

  // ═══════════════════════════════════════════
  // PLATFORM: PER-ORG SUMMARY PAGES
  // ═══════════════════════════════════════════

  if (scope === "platform") {
    for (const org of data.organizations) {
      if (org.learnerCount === 0 && org.completedChapters === 0) continue;

      newPage();
      let oy = sectionHeader(org.name, 25);

      doc.setFontSize(9);
      doc.setTextColor(MUTED);
      doc.text(`${org.type} · ${org.centreCount} centre${org.centreCount !== 1 ? "s" : ""} · ${org.learnerCount} learner${org.learnerCount !== 1 ? "s" : ""}`, margin, oy);
      oy += 8;

      // Metric boxes
      const bw = (contentWidth - 10) / 4;
      drawMetricBox(margin, oy, bw, `${org.completedChapters}/${org.totalChapters}`, "Chapters Done", ORANGE);
      drawMetricBox(margin + bw + 3, oy, bw, `${org.completionRate}%`, "Completion", org.completionRate >= 50 ? GREEN : ORANGE);
      drawMetricBox(margin + (bw + 3) * 2, oy, bw, `${org.activeLearners}`, "Active (7d)", GREEN);
      drawMetricBox(margin + (bw + 3) * 3, oy, bw, org.avgQuizScore != null ? `${org.avgQuizScore}%` : "—", "Quiz Avg", PURPLE);

      oy += 36;

      // This org's centres comparison
      const orgCentres = data.centres.filter((c) => c.orgName === org.name);
      if (orgCentres.length > 0) {
        doc.setFontSize(11);
        doc.setTextColor(HEADING);
        doc.text("Centres", margin, oy);
        oy += 6;

        const items = orgCentres
          .sort((a, b) => b.completionRate - a.completionRate)
          .map((c) => ({
            label: c.name,
            value: c.completionRate,
            suffix: "%",
            annotation: `${c.learnerCount} learners · ${c.mode === "offline" ? "Off" : "On"}`,
            color: c.completionRate >= 50 ? GREEN : ORANGE,
          }));

        oy = drawHorizontalBars(oy, items, 100);
      }

      addFooter();
    }
  }

  // ═══════════════════════════════════════════
  // PER-CENTRE DETAIL PAGES
  // ═══════════════════════════════════════════

  for (const centre of data.centres) {
    if (centre.learnerCount === 0 && centre.completedChapters === 0) continue;

    newPage();

    doc.setFontSize(16);
    doc.setTextColor(HEADING);
    doc.text(centre.name, margin, 25);

    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text(`${centre.mode === "offline" ? "Offline" : "Online"} · ${centre.orgName}${centre.location ? ` · ${centre.location}` : ""}`, margin, 32);
    if (centre.lastSyncAt) {
      doc.text(`Last sync: ${new Date(centre.lastSyncAt).toLocaleString("en-IN", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" })}`, margin, 38);
    }

    doc.setDrawColor(ORANGE);
    doc.setLineWidth(0.4);
    doc.line(margin, 42, margin + 50, 42);

    const bw = (contentWidth - 10) / 4;
    drawMetricBox(margin, 48, bw, `${centre.completedChapters}/${centre.totalChapters}`, "Chapters Done", ORANGE);
    drawMetricBox(margin + bw + 3, 48, bw, `${centre.completionRate}%`, "Completion", centre.completionRate >= 50 ? GREEN : ORANGE);
    drawMetricBox(margin + (bw + 3) * 2, 48, bw, `${centre.watchedLessons}/${centre.totalLessons}`, "Lessons Watched", BLUE);
    drawMetricBox(margin + (bw + 3) * 3, 48, bw, centre.avgQuizScore != null ? `${centre.avgQuizScore}%` : "—", "Quiz Score", PURPLE);

    let cy = 86;

    // Mastery stacked bar for centre
    doc.setFontSize(11);
    doc.setTextColor(HEADING);
    doc.text("Quiz Mastery", margin, cy);
    cy += 5;

    if (centre.quizAttempts > 0) {
      cy = drawStackedBar(cy, [
        { label: "Mastery", value: centre.masteryDistribution.mastery, color: GREEN },
        { label: "Proficient", value: centre.masteryDistribution.proficient, color: BLUE },
        { label: "Developing", value: centre.masteryDistribution.developing, color: YELLOW },
        { label: "Needs Practice", value: centre.masteryDistribution.needs_practice, color: RED },
      ]);
    } else {
      doc.setFontSize(8);
      doc.setTextColor(MUTED);
      doc.text("No quiz attempts", margin, cy);
      cy += 7;
    }

    // Subject Breakdown Table
    if (centre.subjectBreakdown && centre.subjectBreakdown.length > 0) {
      cy += 4;
      doc.setFontSize(11);
      doc.setTextColor(HEADING);
      doc.text("Subject Breakdown", margin, cy);
      cy += 4;

      autoTable(doc, {
        startY: cy,
        margin: { left: margin, right: margin },
        head: [["Subject", "Chapters", "Completion", "Avg Quiz Score"]],
        body: centre.subjectBreakdown.map((s: CentreSubjectBreakdown) => [
          s.name,
          `${s.completedChapters}/${s.totalChapters}`,
          `${s.completionRate}%`,
          s.avgQuizScore != null ? `${s.avgQuizScore}%` : "—",
        ]),
        headStyles: { fillColor: ORANGE, textColor: "#FFFFFF", fontStyle: "bold", fontSize: 8 },
        bodyStyles: { fontSize: 8, textColor: HEADING },
        alternateRowStyles: { fillColor: "#FFF5EB" },
        styles: { cellPadding: 2.5 },
      });
    }

    addFooter();
  }

  // ═══════════════════════════════════════════
  // SAVE
  // ═══════════════════════════════════════════

  const prefix = scope === "platform" ? "EduFleet_Platform_Report" : "EduFleet_Impact_Report";
  const filename = `${prefix}_${now.toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
