"use client";

import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import type { ImpactDashboard } from "./server";

const ORANGE = "#E8871E";
const HEADING = "#2D2117";
const MUTED = "#9C8B7A";
const GREEN = "#22C55E";
const CREAM = "#FFF9F1";

export function generateImpactReport(
  data: ImpactDashboard,
  userName: string,
  orgName: string,
  centreName?: string,
) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const contentWidth = pageWidth - margin * 2;
  const now = new Date();
  const dateStr = now.toLocaleDateString("en-IN", { day: "numeric", month: "long", year: "numeric" });
  const timeStr = now.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" });

  // ─── Helper functions ───

  function addFooter(pageNum: number) {
    doc.setFontSize(8);
    doc.setTextColor(MUTED);
    doc.text("Generated by EduFleet LMS · Confidential", margin, pageHeight - 10);
    doc.text(`Page ${pageNum}`, pageWidth - margin, pageHeight - 10, { align: "right" });
  }

  function drawProgressBar(x: number, y: number, width: number, height: number, percent: number, color: string) {
    doc.setFillColor("#E5E7EB");
    doc.roundedRect(x, y, width, height, height / 2, height / 2, "F");
    if (percent > 0) {
      doc.setFillColor(color);
      doc.roundedRect(x, y, width * (percent / 100), height, height / 2, height / 2, "F");
    }
  }

  function drawMetricBox(x: number, y: number, w: number, value: string, label: string, color: string) {
    doc.setFillColor("#FFFFFF");
    doc.roundedRect(x, y, w, 28, 4, 4, "F");
    doc.setDrawColor("#E8D5C0");
    doc.roundedRect(x, y, w, 28, 4, 4, "S");
    doc.setFontSize(18);
    doc.setTextColor(color);
    doc.text(value, x + w / 2, y + 13, { align: "center" });
    doc.setFontSize(7);
    doc.setTextColor(MUTED);
    doc.text(label, x + w / 2, y + 22, { align: "center" });
  }

  let pageNum = 1;

  // ═══════════════════════════════════════════
  // PAGE 1: COVER
  // ═══════════════════════════════════════════

  doc.setFillColor(CREAM);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  // Logo text
  doc.setFontSize(36);
  doc.setTextColor(HEADING);
  doc.text("edu", pageWidth / 2 - 18, 70, { align: "center" });
  doc.setTextColor(ORANGE);
  doc.text("fleet", pageWidth / 2 + 18, 70, { align: "center" });

  // Title
  doc.setFontSize(28);
  doc.setTextColor(HEADING);
  doc.text("Impact Analytics Report", pageWidth / 2, 100, { align: "center" });

  // Divider
  doc.setDrawColor(ORANGE);
  doc.setLineWidth(0.5);
  doc.line(pageWidth / 2 - 40, 110, pageWidth / 2 + 40, 110);

  // Details
  doc.setFontSize(12);
  doc.setTextColor(MUTED);
  doc.text(dateStr, pageWidth / 2, 125, { align: "center" });
  doc.text(timeStr, pageWidth / 2, 133, { align: "center" });

  doc.setFontSize(11);
  doc.setTextColor(HEADING);
  doc.text(`Generated by: ${userName}`, pageWidth / 2, 155, { align: "center" });
  doc.text(`Organization: ${orgName}`, pageWidth / 2, 165, { align: "center" });
  if (centreName) {
    doc.text(`Centre: ${centreName}`, pageWidth / 2, 175, { align: "center" });
  }

  // Scope
  doc.setFontSize(10);
  doc.setTextColor(MUTED);
  doc.text(`Scope: ${data.scopeLabel}`, pageWidth / 2, 200, { align: "center" });
  doc.text(`${data.totalLearners} learners · ${data.totalChapters} chapters · ${data.totalQuizAttempts} quiz attempts`, pageWidth / 2, 210, { align: "center" });

  // Footer
  doc.setFontSize(8);
  doc.setTextColor(MUTED);
  doc.text("Confidential · For internal use only", pageWidth / 2, pageHeight - 20, { align: "center" });

  addFooter(pageNum);

  // ═══════════════════════════════════════════
  // PAGE 2: EXECUTIVE SUMMARY
  // ═══════════════════════════════════════════

  doc.addPage();
  pageNum++;
  doc.setFillColor(CREAM);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  doc.setFontSize(20);
  doc.setTextColor(HEADING);
  doc.text("Executive Summary", margin, 25);

  doc.setDrawColor(ORANGE);
  doc.setLineWidth(0.3);
  doc.line(margin, 30, margin + 60, 30);

  // 4 metric boxes
  const boxW = (contentWidth - 15) / 4;
  drawMetricBox(margin, 40, boxW, `${data.completedChapters}/${data.totalChapters}`, "Chapters Completed", ORANGE);
  drawMetricBox(margin + boxW + 5, 40, boxW, `${data.completionRate}%`, "Completion Rate", data.completionRate >= 50 ? GREEN : ORANGE);
  drawMetricBox(margin + (boxW + 5) * 2, 40, boxW, `${data.activeLearners}`, "Active Learners (7d)", GREEN);
  drawMetricBox(margin + (boxW + 5) * 3, 40, boxW, data.avgQuizScore != null ? `${data.avgQuizScore}%` : "—", "Avg Quiz Score", "#8B5CF6");

  // Auto-generated summary paragraph
  let y = 80;
  doc.setFontSize(10);
  doc.setTextColor(HEADING);

  const summaryLines = [];
  summaryLines.push(`This report covers ${data.totalLearners} learner${data.totalLearners !== 1 ? "s" : ""} across ${data.centres.length} centre${data.centres.length !== 1 ? "s" : ""}.`);
  summaryLines.push(`Overall completion rate is ${data.completionRate}% with ${data.completedChapters} out of ${data.totalChapters} chapters completed.`);
  if (data.activeLearners > 0) {
    summaryLines.push(`${data.activeLearners} learner${data.activeLearners !== 1 ? "s were" : " was"} active in the last 7 days.`);
  } else {
    summaryLines.push("No learners were active in the last 7 days.");
  }
  if (data.totalQuizAttempts > 0) {
    summaryLines.push(`${data.totalQuizAttempts} quiz attempt${data.totalQuizAttempts !== 1 ? "s" : ""} recorded with an average score of ${data.avgQuizScore}%.`);
  }
  const lowPerformers = data.centres.filter((c) => c.completionRate < 30 && c.learnerCount > 0);
  if (lowPerformers.length > 0) {
    summaryLines.push(`${lowPerformers.length} centre${lowPerformers.length !== 1 ? "s are" : " is"} below 30% completion and may need attention.`);
  }

  for (const line of summaryLines) {
    doc.text(line, margin, y);
    y += 7;
  }

  // Quiz Mastery Distribution
  y += 10;
  doc.setFontSize(14);
  doc.setTextColor(HEADING);
  doc.text("Quiz Mastery Distribution", margin, y);
  y += 8;

  if (data.totalQuizAttempts > 0) {
    const masteryData = [
      { label: "Mastery (90%+)", count: data.masteryDistribution.mastery, color: GREEN },
      { label: "Proficient (70-89%)", count: data.masteryDistribution.proficient, color: "#3B82F6" },
      { label: "Developing (50-69%)", count: data.masteryDistribution.developing, color: "#EAB308" },
      { label: "Needs Practice (<50%)", count: data.masteryDistribution.needs_practice, color: "#EF4444" },
    ];
    for (const item of masteryData) {
      const pct = Math.round((item.count / data.totalQuizAttempts) * 100);
      doc.setFontSize(9);
      doc.setTextColor(HEADING);
      doc.text(item.label, margin, y + 3);
      drawProgressBar(margin + 50, y, 80, 4, pct, item.color);
      doc.setFontSize(8);
      doc.setTextColor(MUTED);
      doc.text(`${item.count} (${pct}%)`, margin + 135, y + 3);
      y += 9;
    }
  } else {
    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text("No quiz attempts recorded.", margin, y);
    y += 7;
  }

  addFooter(pageNum);

  // ═══════════════════════════════════════════
  // PAGE 3: CENTRE PERFORMANCE TABLE
  // ═══════════════════════════════════════════

  doc.addPage();
  pageNum++;
  doc.setFillColor(CREAM);
  doc.rect(0, 0, pageWidth, pageHeight, "F");

  doc.setFontSize(20);
  doc.setTextColor(HEADING);
  doc.text("Centre Performance", margin, 25);
  doc.setDrawColor(ORANGE);
  doc.line(margin, 30, margin + 60, 30);

  autoTable(doc, {
    startY: 38,
    margin: { left: margin, right: margin },
    head: [["Centre", "Mode", "Learners", "Active 7d", "Completion", "Chapters", "Quiz Avg", "Last Activity"]],
    body: data.centres.map((c) => [
      c.name,
      c.mode === "offline" ? "Offline" : "Online",
      String(c.learnerCount),
      String(c.activeLearners),
      `${c.completionRate}%`,
      `${c.completedChapters}/${c.totalChapters}`,
      c.avgQuizScore != null ? `${c.avgQuizScore}%` : "—",
      c.lastActivityAt ? new Date(c.lastActivityAt).toLocaleDateString("en-IN", { day: "numeric", month: "short" }) : "—",
    ]),
    headStyles: {
      fillColor: ORANGE,
      textColor: "#FFFFFF",
      fontStyle: "bold",
      fontSize: 8,
    },
    bodyStyles: {
      fontSize: 8,
      textColor: HEADING,
    },
    alternateRowStyles: {
      fillColor: "#FFF5EB",
    },
    styles: {
      cellPadding: 3,
    },
  });

  addFooter(pageNum);

  // ═══════════════════════════════════════════
  // PAGE 4+: PER-CENTRE DETAIL PAGES
  // ═══════════════════════════════════════════

  for (const centre of data.centres) {
    if (centre.learnerCount === 0 && centre.completedChapters === 0) continue;

    doc.addPage();
    pageNum++;
    doc.setFillColor(CREAM);
    doc.rect(0, 0, pageWidth, pageHeight, "F");

    doc.setFontSize(16);
    doc.setTextColor(HEADING);
    doc.text(centre.name, margin, 25);

    doc.setFontSize(9);
    doc.setTextColor(MUTED);
    doc.text(`${centre.mode === "offline" ? "Offline" : "Online"} · ${centre.orgName}${centre.location ? ` · ${centre.location}` : ""}`, margin, 32);
    if (centre.lastSyncAt) {
      doc.text(`Last sync: ${new Date(centre.lastSyncAt).toLocaleString("en-IN", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" })}`, margin, 38);
    }

    doc.setDrawColor(ORANGE);
    doc.line(margin, 42, margin + 50, 42);

    // Metric boxes
    const bw = (contentWidth - 10) / 4;
    drawMetricBox(margin, 48, bw, `${centre.completedChapters}/${centre.totalChapters}`, "Chapters Done", ORANGE);
    drawMetricBox(margin + bw + 3, 48, bw, `${centre.completionRate}%`, "Completion", centre.completionRate >= 50 ? GREEN : ORANGE);
    drawMetricBox(margin + (bw + 3) * 2, 48, bw, `${centre.watchedLessons}/${centre.totalLessons}`, "Lessons Watched", "#3B82F6");
    drawMetricBox(margin + (bw + 3) * 3, 48, bw, centre.avgQuizScore != null ? `${centre.avgQuizScore}%` : "—", "Quiz Score", "#8B5CF6");

    // Mastery for this centre
    let cy = 86;
    doc.setFontSize(11);
    doc.setTextColor(HEADING);
    doc.text("Quiz Mastery", margin, cy);
    cy += 6;

    if (centre.quizAttempts > 0) {
      const items = [
        { label: "Mastery", count: centre.masteryDistribution.mastery, color: GREEN },
        { label: "Proficient", count: centre.masteryDistribution.proficient, color: "#3B82F6" },
        { label: "Developing", count: centre.masteryDistribution.developing, color: "#EAB308" },
        { label: "Needs Practice", count: centre.masteryDistribution.needs_practice, color: "#EF4444" },
      ];
      for (const item of items) {
        const pct = Math.round((item.count / centre.quizAttempts) * 100);
        doc.setFontSize(8);
        doc.setTextColor(HEADING);
        doc.text(item.label, margin, cy + 2.5);
        drawProgressBar(margin + 35, cy, 60, 3, pct, item.color);
        doc.text(`${item.count}`, margin + 100, cy + 2.5);
        cy += 7;
      }
    } else {
      doc.setFontSize(8);
      doc.setTextColor(MUTED);
      doc.text("No quiz attempts", margin, cy);
      cy += 7;
    }

    addFooter(pageNum);
  }

  // ═══════════════════════════════════════════
  // SAVE
  // ═══════════════════════════════════════════

  const filename = `EduFleet_Impact_Report_${now.toISOString().slice(0, 10)}.pdf`;
  doc.save(filename);
}
